INSERT INTO "C##TWOSOME_ADMIN"."TB_ADMIN_MEMBER_INFO" (ADMIN_ID, ADMIN_PASSWORD, ADMIN_NM, ADMIN_MAIL) VALUES ('admin100', '18141814', '½´ÆÛ°ü¸®ÀÚ', 'testtest@hanmail.net')


INSERT INTO "C##TWOSOME_ADMIN"."TB_ADMIN_MEMBER_INFO" (ADMIN_ID, ADMIN_PASSWORD, ADMIN_NM, ADMIN_MAIL) VALUES ('admin_goods', '00000000', '»óÇ°°ü¸®ÀÚ', 'testtest@hanmail.net')

